using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json.Linq;
using TopSolidMcpServer.Protocol;
using TopSolidMcpServer.Protocol.Models;

namespace TopSolidMcpServer.Tools
{
    /// <summary>
    /// Returns the TopSolid API changelog for a given version (or the latest),
    /// as generated by the sync-topsolid-api pipeline. Helps Claude Code /
    /// developers discover new methods, breaking changes, and deprecations.
    /// </summary>
    public class WhatsNewTool
    {
        private static readonly Regex VersionRe = new Regex(@"^\d+\.\d+(?:\.\d+){0,2}$");
        private static readonly Regex ChangelogFileRe = new Regex(@"^changelog-(\d+\.\d+(?:\.\d+){0,2})\.md$", RegexOptions.IgnoreCase);

        public void Register(McpToolRegistry registry)
        {
            registry.RegisterTool(new McpToolDescriptor
            {
                Name = "topsolid_whats_new",
                Description = "Returns the TopSolid API changelog for a given version " +
                    "(new methods, breaking changes, deprecations) as generated by the " +
                    "sync-topsolid-api pipeline. Omit the version to get the latest.",
                InputSchema = new JObject
                {
                    ["type"] = "object",
                    ["properties"] = new JObject
                    {
                        ["version"] = new JObject
                        {
                            ["type"] = "string",
                            ["description"] = "TopSolid version (e.g. '7.21.164.0'). Omit for the latest available."
                        }
                    }
                }
            }, Execute);
        }

        /// <summary>
        /// Execute: load and return the changelog markdown.
        /// </summary>
        public string Execute(JObject arguments)
        {
            try
            {
                string version = arguments?["version"]?.ToString()?.Trim();
                string dataDir = FindDataDir();
                if (dataDir == null)
                {
                    return "Error: data directory not found.";
                }

                if (string.IsNullOrEmpty(version))
                {
                    version = FindLatestChangelogVersion(dataDir);
                    if (version == null)
                    {
                        return "No changelog found in " + dataDir + ". " +
                            "Run the sync-topsolid-api pipeline to generate one.";
                    }
                }

                if (!VersionRe.IsMatch(version))
                {
                    return "Error: invalid version format '" + version + "'.";
                }

                string path = Path.Combine(dataDir, "changelog-" + version + ".md");
                if (!File.Exists(path))
                {
                    var available = ListAvailableVersions(dataDir);
                    return "No changelog for version '" + version + "'. " +
                        (available.Length > 0 ? "Available: " + string.Join(", ", available) : "None available.");
                }

                string content = File.ReadAllText(path);
                // Include header in the result
                var sb = new StringBuilder();
                sb.AppendLine("=== Changelog for TopSolid " + version + " ===");
                sb.AppendLine();
                sb.Append(content);
                return sb.ToString();
            }
            catch (Exception ex)
            {
                Console.Error.WriteLine("[WhatsNewTool] Error: " + ex.Message);
                return "Error: " + ex.Message;
            }
        }

        private static string FindDataDir()
        {
            string baseDir = AppDomain.CurrentDomain.BaseDirectory;

            // Candidates in priority order. We prefer the one that actually
            // contains changelog-*.md files, then any data/ dir as fallback.
            string[] candidates = new[]
            {
                Path.Combine(baseDir, "data"),
                Path.Combine(baseDir, "..", "..", "..", "..", "data"),  // dev: src/bin/Release/net48 -> project/data
            };

            // First pass: prefer a dir containing changelog-*.md
            foreach (var c in candidates)
            {
                if (!Directory.Exists(c)) continue;
                if (Directory.EnumerateFiles(c, "changelog-*.md").Any())
                    return Path.GetFullPath(c);
            }

            // Second pass: return any existing data dir (even empty)
            foreach (var c in candidates)
            {
                if (Directory.Exists(c)) return Path.GetFullPath(c);
            }

            return null;
        }

        private static string FindLatestChangelogVersion(string dataDir)
        {
            var versions = ListAvailableVersions(dataDir);
            if (versions.Length == 0) return null;
            // Sort by semver descending
            return versions
                .OrderByDescending(v => ParseVersion(v))
                .First();
        }

        private static string[] ListAvailableVersions(string dataDir)
        {
            if (!Directory.Exists(dataDir)) return new string[0];
            return Directory.EnumerateFiles(dataDir, "changelog-*.md")
                .Select(p =>
                {
                    var m = ChangelogFileRe.Match(Path.GetFileName(p));
                    return m.Success ? m.Groups[1].Value : null;
                })
                .Where(v => v != null)
                .ToArray();
        }

        private static Version ParseVersion(string v)
        {
            try { return new Version(v); }
            catch { return new Version(0, 0); }
        }
    }
}
